name = "anime-uke"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "anime-uke-db"
database_id = ""

[[kv_namespaces]]
binding = "KV"
id = ""

[pages]
build_command = "echo 'No build needed'"
